export const ISSUES = {
  LOAD: "ISSUES_LOAD",
  RESPONSE: "ISSUES_RESPONSE",
  ERROR: "ISSUES_ERROR",
};

export const INCREMENT = {
  WATCH: "WATCH_COUNT",
  STAR: "STAR_COUNT",
  FORK: "FORK_COUNT",
};
